# -*- coding: utf-8 -*-
"""CintaP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RX-mjtEmiDoGA6RuQNq8ygqgRn-g-Krz
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_excel("cinta.xlsx")

data.columns = ["ID", "Name", "Quiz", "Midterm", "Final", "Final_Score", "Grade"]

print(data)

# tabel frekuensi
print("\nFrekuensi Grade")
print(data["Grade"].value_counts())

# line chart
plt.figure(figsize=(10,5))
plt.plot(data["Name"], data["Final_Score"], marker="o")
plt.title("Final Score Mahasiswa")
plt.xlabel("Nama")
plt.ylabel("Final Score")
plt.xticks(rotation=90)
plt.show()

# bar chart
grade = data["Grade"].value_counts()

plt.figure(figsize=(7,5))
plt.bar(grade.index, grade.values)
plt.title("Frekuensi Grade")
plt.xlabel("Grade")
plt.ylabel("Frekuensi")
plt.show()

# pie chart
plt.figure(figsize=(7,7))
plt.pie(grade.values, labels=grade.index, autopct="%1.1f%%")
plt.title("Persentase Grade")
plt.show()

# statistik deskriptif
print("\nStatistika Deskriptif")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].describe())

print("\nMean")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].mean())

print("\nMedian")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].median())

print("\nModus")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].mode().iloc[0])

print("\nVariance")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].var())

print("\nStandard Deviation")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].std())

print("\nSkewness")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].skew())

print("\nKurtosis")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].kurt())

print("\nStandard Error")
print(data[["Quiz", "Midterm", "Final", "Final_Score"]].sem())

